### PR TITLE
New Features:

### PR DESCRIPTION
**Pull request by FloThinksPi**
-Added Abillity to not show Artist in song Title(-a)
-Added Artist Parsing from Title(-m) maybe User is not Artist -> TODO other seperators than minus
    e.g. "tiasu - plummet" gets parsed to artist=tiasu song=plummet
-Added SubfolderSystem for each Artist/User and Playlists are subfolders of them(-s)
-Added Abillity to make Folders by User and not by Artist(-k)
-Made Playlistsname save as albumname
-Adaptet the "Already Downloaded" part to the filesystem too.

Need some intensive testing before merging! 
Works fine for me , didnt test Groups btw.

Greetings from Germany,
Flo

### CODE REVIEW

**Comment by FloThinksPi** [comment]
i think experimental branch makes sense , cant say how stable / without errors it runs because i have no time for excessive testing with all possible cases (groups and stacked playlists etc.)
runs good so far , downloading with it right now:
scdl -l https://soundcloud.com/mrsuicidesheep/ -c -m -s -k -p ~/SoundCloud/

Great work you did ;)

**Comment by flyingrub** [comment]
hi @FloThinksPi, can you tell me why you prefer the bash one ? :)

**Comment by FloThinksPi** [comment]
I Like the Linux Way of doing things verry much :) 
Straight ,clear and verryfast(in coding). 
I also did a lot of Python (RPI), but dislikes the Syntax with spaces.
Usually i take C for the fast and non object oriented stuff and Java or C# for object oriented work .
so its all just about preferences :D

**Comment by flyingrub** [comment]
"Straight ,clear and verryfast" sounds like python to me, not bash ^^

**Comment by FloThinksPi** [comment]
@flyingrub 
Yep have already enough batch for now :D , going to fix my erros and then having fun with Python ;)

Seems like These Feautres are also not in the Py version right ? 
-Batch Processing URLs(Cfg)
-Subfoldersystem
-Title Parsing to get (Real)Artists
:D

**Comment by flyingrub** [comment]
there is the subfolder for the playlist and i don't understand the first one, but let's talk about it on the right repo ;)

**Pull request merged**
